### ISSUE TITLE
Support .NET Standard in csharp_nunit_test

### ISSUE THREAD

**Issue by j3parker** [Brightspace/rules_csharp#27]
In #26 I realized that we don't actually support .NET Standard tests because we create an executable (Bazel wants tests to be executable) using NUnitLite.

We could, instead, produce a DLL without NUnitLite, and separately an exe that loads the test DLL (and its dependencies) at runtime. That exe could be the latest .NET Core framework.

Related issues:

* #9: we need to create a general wrapper for executables used in `bazel run`/`bazel test` that can load DLLs from arbitrary folders in the output root (not something that works out of the box with C#)
* #8: we need to be able to use `csharp_binary` for .NET Core

**Comment by jimevans** [comment]
I think it's a reasonable limitation to support only .NET Core unit tests for testing libraries that are .NET Standard libraries. Since the Visual Studio MSTest framework doesn't support testing .NET Standard test projects directly, my suspicion is that most users who have a .NET Standard library already target their test projects for that library as .NET Core.

**Comment by j3parker** [comment]
Oh ya, I was totally over-thinking this. Your tests don't need to be written against .NET Standard to test a .NET Standard library. Got it.
