### ISSUE TITLE
Allow checked in nupkg to be used in nuget_package

### ISSUE THREAD

**Issue by j3parker** [Brightspace/rules_csharp#29]
`nuget_package` is built on top of `http_archive` which allows a file to be used in place of a URL.

We should mimic this so that people can check their nupkg's in/get them locally if they desire. Maybe this could be an optional `src` attr, and use it in place of nuget.org?

**Comment by omsmith** [comment]
Since we discussed something similar came up today, just want to note that relative file urls _do_ work if used in the form `file:foo.bar` (no `//`).

Parameter wise, I think it makes sense to just fall in line with `http_archive` and be `ONE OF [package AND version] OR [url] OR [urls]`. This might look like
```python
nuget_package(
    name = "foo",
    url = "file:packages/foo.nupkg",
    sha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
)
```
