### ISSUE TITLE
Use .NET 3.5 reference assemblies once they exist in the package

### ISSUE THREAD

**Issue by j3parker** [Brightspace/rules_csharp#99]
See https://github.com/dotnet/core-sdk/issues/2022

As of #88 we support frameworks like .NET 3.5 when imported from NuGet packages, but we can't compile anything (if you dep on `@net` packages... which you do by default). Once Microsoft adds .NET 3.5 to their package we should wire it up.

**Comment by j3parker** [comment]
Well, they've officially said this won't be supported. So I'm going to close this.

**Comment by jnm2** [comment]
Because [net35 is still in support and net40 and net20 are not](https://support.microsoft.com/en-us/help/17455/lifecycle-faq-net-framework), and this targeting pack includes net20 and net40 but not net35, and because I'm familiar with the pain of not having the choice to stop supporting net35, I created a community package to go along with these:

https://www.nuget.org/packages/jnm2.ReferenceAssemblies.net35

There doesn't seem to be any technical limitation distinguishing this package from the Microsoft packages, and my integration tests show this working fine:

##### Example.csproj

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net35;net40;netstandard2.0;netcoreapp3.0</TargetFrameworks>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.0-*" />
    <PackageReference Include="jnm2.ReferenceAssemblies.net35" Version="1.0.0-*" />
  </ItemGroup>

</Project>
```

##### ClassUsingSystemLinq.cs

```cs
using System.Linq;

public class ClassUsingSystemLinq
{
    public ClassUsingSystemLinq()
    {
        Enumerable.Empty<int>();
    }
}
```

This solves the problem of having to use VSWhere to find MSBuild when compiling for net35 on Windows and the problem of having to use Mono's MSBuild when compiling for net35 on macOS and Linux. `dotnet build` all the way. Here's to less infrastructure fighting. Happy coding!
